services:
  # Base de datos PostgreSQL para almacenar los datos procesados
  db:
    image: postgres:15-alpine
    container_name: london_sentinel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password_secreta
      POSTGRES_DB: london_crime_gold
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Fase 1: Ingesta de datos desde BigQuery
  ingesta:
    build: .
    volumes:
      - .:/app
    command: python src/ingestion/ingesta_london_crime.py

  # Fase 2: Limpieza y Transformación (Espera a que termine la ingesta)
  limpieza:
    build: .
    depends_on:
      ingesta:
        condition: service_completed_successfully
    volumes:
      - .:/app
    command: python src/processing/limpieza_london_crime.py

  # Fase 3: Validación estructural y semántica (Espera a que termine la limpieza)
  validacion:
    build: .
    depends_on:
      limpieza:
        condition: service_completed_successfully
    volumes:
      - .:/app
    command: python src/processing/validacion_london_crime.py

  # Fase 4: Servidor de Jupyter Notebook dentro del contenedor
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      validacion:
        condition: service_completed_successfully
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''

# Configuración global de almacenamiento persistente para PostgreSQL
volumes:
  postgres_data: